version: '3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-5000}:5000'
      - '${APP_DEBUG_PORT:-9009}:9009'
    volumes:
      - './:/app'
    depends_on:
      - database
    networks:
      - financial_data
    env_file:
      - .env
    entrypoint: ./financial/serve.sh ${APP_DEBUG}

  database:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD:-root}'
      POSTGRES_USER: '${DB_USER:-root}'
      POSTGRES_DB: '${DB_NAME:-db_name}'
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - financial_data
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data

networks:
  financial_data:
    driver: bridge