# Generated by Django 4.1.9 on 2023-06-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='financialdata',
            unique_together={('symbol', 'date')},
        ),
    ]
